### ISSUE TITLE
Update env

### ISSUE THREAD

**Issue by kcpevey** [Quansight/omnisci-examples#5]
* holoviews from PR holoviz/holoviews#4517
* ibis - from commit 10d40305defc7337d217b595c4b6b74e66d153da
* hvplot from PR holoviz/hvplot#507
* python-graphviz
* pydot
* geoviews ( will pull in holoviews which you'll have to manually remove with --force)

cross reference: https://github.com/Quansight/omnisci-datascience-installer/issues/2

**Comment by xmnlab** [comment]
done
